Updated Master Driver docs structure in RTD
VOLTTRON/volttron pull request #2516
Opened 2020-11-04 19:14 UTC by jklarson

# Description

Updated the structure of the Master driver docs in agent and driver sections per feedback.  Includes fixes for a few more minor comments.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Tested using local Sphinx build

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2020-11-04 19:38 UTC, craig8 requested changes

2020-11-04 19:38 UTC, craig8 commented on docs/source/agent-framework/core-service-agents/master-driver/master-driver-agent.rst
> +The Master Driver like all other agents, requires a configuration file (described in brief below).  Once the user
remove like all other agents...

2020-11-04 19:38 UTC, craig8 commented on docs/source/agent-framework/core-service-agents/master-driver/master-driver-agent.rst
> +Driver should be sufficient for most users.
get rid of should be ...

just add as follows or some other wording that says look at the example.

2020-11-04 19:38 UTC, craig8 commented on docs/source/agent-framework/core-service-agents/master-driver/master-driver-agent.rst
> +The Master Driver like all other agents, requires a configuration file (described in brief below).  Once the user
Add configuration file to set global settings for all drivers.

2020-11-04 19:38 UTC, craig8 commented on docs/source/agent-framework/core-service-agents/master-driver/master-driver-agent.rst
> +agent:
Remove similar to any other agent.

Just is deployed using the following:

2020-11-05 00:32 UTC, shwethanidd approved these changes

2020-11-05 00:32 UTC, merged