Bugfix/control connection check
VOLTTRON/volttron pull request #2825
Opened 2021-11-17 21:16 UTC by sgilbride

# Description

Provides a check if the platform is running for control methods.
Adds checks to appropriate methods so vctl will behave correctly in cases where the platform is or is not running.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested with pytest locally running control_tests test directory.

2021-11-30 22:39 UTC, craig8 requested changes
I like this decorator.

The documentation for needs_connection should specify that opts must be the first argument to func which is passed in and that the connection must exist...

So document the arguments to this as well as the func should be :callable I believe.

2021-11-30 22:39 UTC, craig8 commented on volttron/platform/control.py
> +    # if not conn:
Remove commented out code..

2021-12-15 20:35 UTC, sgilbride commented on volttron/platform/control.py
> +    # if not conn:
Fixed!

2022-01-06 20:47 UTC, craig8 approved these changes

2022-01-06 20:47 UTC, merged