Releases/9.0rc0
VOLTTRON/volttron pull request #3157
Opened 2024-03-19 18:58 UTC by riley206

# Description

fixed log stat agent to actually report every 24 hours as well as report the mean. Log stat agent now also has a default config to fall back on if no config is provided or values are missing from the config. 

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

ran the log stat agent 9.0rc0 branch of volttron. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-17 23:20 UTC, craig8 requested changes

2024-05-17 23:20 UTC, craig8 commented on services/ops/LogStatisticsAgent/logstatisticsagent/agent.py
> +import time
time is not used anywhere that I have found.

2024-05-17 23:20 UTC, craig8 commented on services/ops/LogStatisticsAgent/logstatisticsagent/agent.py
> +        if not self.configured:
Remove this onstart block and just use the configure main section.  There should be no need for both blocks.

2024-06-28 19:20 UTC, shwethanidd approved these changes

2024-07-31 20:40 UTC, merged